# Generated by Django 5.2.3 on 2026-03-29 03:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('devices', '0001_initial'),
        ('inference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organ_type', models.CharField(choices=[('leaf', 'Leaf'), ('fruit', 'Fruit')], max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('closed', 'Closed')], default='new', max_length=20)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('source_message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('top1_label', models.CharField(blank=True, max_length=255)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('captured_at', models.DateTimeField()),
                ('received_at', models.DateTimeField()),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('extra_metadata', models.JSONField(blank=True, default=dict)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='devices.device')),
                ('inference_index', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='inference.inferenceindex')),
                ('predicted_disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='catalog.disease')),
            ],
            options={
                'ordering': ('-captured_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='InspectionMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rank_order', models.PositiveIntegerField()),
                ('matched_label', models.CharField(max_length=255)),
                ('similarity_score', models.FloatField()),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_matches', to='catalog.disease')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='inspections.inspection')),
            ],
            options={
                'ordering': ('rank_order',),
                'constraints': [models.UniqueConstraint(fields=('inspection', 'rank_order'), name='unique_match_rank_per_inspection')],
            },
        ),
    ]
