# Generated by Django 5.2.3 on 2026-04-16 04:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('devices', '0001_initial'),
        ('inference', '0002_remove_inferenceindex_unique_index_name_per_model_version_and_more'),
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name='inspection',
            constraint=models.CheckConstraint(condition=models.Q(('confidence_score__isnull', True), models.Q(('confidence_score__gte', 0), ('confidence_score__lte', 1)), _connector='OR'), name='inspection_confidence_score_between_0_and_1_or_null'),
        ),
    ]
