# Generated by Django 5.2.3 on 2026-05-24 23:58

import apps.inspections.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_latitude_device_local_x_device_local_y_and_more'),
        ('inspections', '0003_inspection_unique_source_message_id_when_present'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceImageRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_message_id', models.CharField(db_index=True, max_length=255)),
                ('image_id', models.CharField(blank=True, max_length=255)),
                ('local_image_ref', models.CharField(blank=True, max_length=255)),
                ('reason', models.CharField(choices=[('disease_alert', 'Disease alert'), ('review_required', 'Review required')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('failed', 'Failed'), ('expired', 'Expired'), ('not_found', 'Not found')], db_index=True, default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_metadata', models.JSONField(blank=True, default=dict)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_image_requests', to='devices.device')),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_request', to='inspections.inspection')),
            ],
            options={
                'ordering': ('-requested_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='InspectionEvidenceImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_message_id', models.CharField(db_index=True, max_length=255)),
                ('image', models.FileField(upload_to=apps.inspections.models.inspection_evidence_upload_to)),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('image_sha256', models.CharField(max_length=64)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_evidence_images', to='devices.device')),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_image', to='inspections.inspection')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_image', to='inspections.evidenceimagerequest')),
            ],
            options={
                'ordering': ('-uploaded_at', '-created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='evidenceimagerequest',
            index=models.Index(fields=['device', 'status'], name='evidence_req_device_status_idx'),
        ),
    ]
