# Generated by Django 5.2.3 on 2026-08-30 14:08

import apps.inspections.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_evidenceimagerequest_inspectionevidenceimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionevidenceimage',
            name='image',
            field=models.FileField(max_length=500, upload_to=apps.inspections.models.inspection_evidence_upload_to),
        ),
    ]
