# Generated by Django 5.2.3 on 2026-03-29 03:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=100)),
                ('framework', models.CharField(blank=True, max_length=100)),
                ('artifact_path', models.CharField(blank=True, max_length=500)),
                ('checksum', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name', 'version'),
                'constraints': [models.UniqueConstraint(fields=('name', 'version'), name='unique_model_version_per_name')],
            },
        ),
        migrations.CreateModel(
            name='InferenceIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('backend', models.CharField(blank=True, max_length=100)),
                ('similarity_metric', models.CharField(blank=True, max_length=50)),
                ('dimension', models.PositiveIntegerField()),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('artifact_path', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indexes', to='inference.modelversion')),
            ],
            options={
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(fields=('model_version', 'name'), name='unique_index_name_per_model_version')],
            },
        ),
    ]
