# Generated by Django 5.2.3 on 2026-03-29 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inferenceindex',
            name='unique_index_name_per_model_version',
        ),
        migrations.RemoveField(
            model_name='inferenceindex',
            name='artifact_path',
        ),
        migrations.RemoveField(
            model_name='inferenceindex',
            name='backend',
        ),
        migrations.RemoveField(
            model_name='inferenceindex',
            name='dimension',
        ),
        migrations.RemoveField(
            model_name='inferenceindex',
            name='item_count',
        ),
        migrations.RemoveField(
            model_name='inferenceindex',
            name='similarity_metric',
        ),
        migrations.AddField(
            model_name='inferenceindex',
            name='index_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='inferenceindex',
            name='loaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inferenceindex',
            name='metadata_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='inferenceindex',
            name='organ_type',
            field=models.CharField(choices=[('leaf', 'Leaf'), ('fruit', 'Fruit')], default='leaf', max_length=20),
        ),
        migrations.AddField(
            model_name='inferenceindex',
            name='threshold_default',
            field=models.FloatField(default=0.8),
        ),
        migrations.AddField(
            model_name='inferenceindex',
            name='top_k_default',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddConstraint(
            model_name='inferenceindex',
            constraint=models.UniqueConstraint(fields=('model_version', 'organ_type', 'name'), name='unique_index_name_per_model_version_and_organ'),
        ),
    ]
