# Generated by Django 5.2.3 on 2026-05-11 11:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_normalize_disease_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseMapProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_infectious', models.BooleanField(default=False)),
                ('spread_category', models.CharField(choices=[('none', 'None'), ('fungal', 'Fungal'), ('bacterial', 'Bacterial'), ('viral', 'Viral'), ('oomycete', 'Oomycete'), ('physiological', 'Physiological'), ('environmental', 'Environmental'), ('unknown', 'Unknown')], default='none', max_length=32)),
                ('transmission_mode', models.CharField(choices=[('none', 'None'), ('splash', 'Splash'), ('airborne', 'Airborne'), ('contact', 'Contact'), ('soil', 'Soil'), ('seed', 'Seed'), ('vector_thrips', 'Vector thrips'), ('vector_whitefly', 'Vector whitefly'), ('humidity_related', 'Humidity related'), ('water_stress', 'Water stress'), ('nutrient_water_imbalance', 'Nutrient/water imbalance'), ('development_disorder', 'Development disorder'), ('unknown', 'Unknown')], default='none', max_length=64)),
                ('zone_type', models.CharField(choices=[('none', 'None'), ('infection_zone', 'Infection zone'), ('risk_zone', 'Risk zone'), ('vector_risk_zone', 'Vector risk zone'), ('agronomic_risk_zone', 'Agronomic risk zone')], default='none', max_length=32)),
                ('spread_radius_m', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=16)),
                ('map_color', models.CharField(blank=True, max_length=16)),
                ('map_label', models.CharField(blank=True, max_length=120)),
                ('short_map_description', models.TextField(blank=True)),
                ('source_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('disease', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='map_profile', to='catalog.disease')),
            ],
            options={
                'ordering': ('disease__organ_type', 'disease__name'),
                'constraints': [models.CheckConstraint(condition=models.Q(('spread_radius_m__gte', 0)), name='disease_map_profile_spread_radius_non_negative')],
            },
        ),
    ]
