# Generated by Django 5.2.3 on 2026-03-29 03:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inference', '0002_remove_inferenceindex_unique_index_name_per_model_version_and_more'),
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('vector', models.JSONField()),
                ('notes', models.TextField(blank=True)),
                ('inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embedding_records', to='inspections.inspection')),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='embedding_records', to='inference.modelversion')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
